import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TanstackReactQueryProvider } from "@/lib/provider";
import { ReactFlowProvider } from "@xyflow/react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "MindMap Generator",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <TanstackReactQueryProvider>
                    <ReactFlowProvider>{children}</ReactFlowProvider>
                </TanstackReactQueryProvider>
            </body>
        </html>
    );
}
